apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins-workers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jenkins-workers
  name: jenkins-worker-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "secrets", "services"]
    verbs: ["create", "get", "watch", "list", "delete", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-worker-rolebinding
  namespace: jenkins-workers
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: jenkins-workers
  - kind: ServiceAccount
    name: jenkins
    namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-worker-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: database
  name: jenkins-worker-secret-access
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-worker-secret-rolebinding
  namespace: database
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: jenkins-workers
  - kind: ServiceAccount
    name: jenkins
    namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-worker-secret-access
  apiGroup: rbac.authorization.k8s.io
