apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: database
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "PostgreSQL DevOps",
          "Group": "Servers",
          "Host": "postgresql.database.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "SSLMode": "prefer",
          "SSLCert": "<STORAGE_DIR>/.postgresql/postgresql.crt",
          "SSLKey": "<STORAGE_DIR>/.postgresql/postgresql.key",
          "SSLCompression": 0,
          "Timeout": 10,
          "UseSSHTunnel": 0,
          "TunnelPort": "22",
          "TunnelAuthentication": 0
        }
      }
    } 