apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: database
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=       # Base64 encoded: "postgres"
  postgres-password: YWRtaW4xMjMh # Base64 encoded: "admin123!"
  postgres-db: ZGV2b3BzZGI=               # Base64 encoded: "devopsdb"